services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    
  apache:
    image: php:8.3-apache
    restart: always
    ports: 
      - 80:80
    volumes:
      - ./html:/usr/local/apache2/htdocs/

volumes: # Définition des volumes
  dbdata:

networks: # Définition des réseaux
  mynetwork: